# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ca29b8c17f637943d841fb5643bf507055e15aa1497980227c589d12f53a7e8ce522cecac1b2596a65f0d461b901cbe149e677ca8ff7d6a50da61cb5eda53f9

test:
  secret_key_base: dd0c82557366fbbfd197627aca228927e35186f215a70eb7bf109bb516eb043dec6167ad5ad91e37d7b4ee6b2cdd5241ca73b89828333fd390c6dc4151a7aaa5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
